version: '3.8'
services:
  bq_emulator_postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bq_emulator
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: